language: erlang
otp_release:
  - 19.3
  - 20.3
  - 21.3
  - 22.0
install:
  - wget https://s3.amazonaws.com/rebar3/rebar3
  - chmod +x rebar3
  - export PATH=$PWD:$PATH
script:
  - rebar3 do compile, clojerl test
notifications:
  email: false
